### PR TITLE
Adding missing transmission signals

### PR DESCRIPTION
**Pull request by erikbosch**

### CODE REVIEW

**Comment by SebastianSchildt** [comment]
Again. I am not a car guy :) 

Noticed two things:

"Is electrical powertrain mechanically connected" is not true for those Toyota HSD hybrids is it? I think they have some magic planetary gearing where both drives are always mechanically connected. At least this desigm is probably still the most hybrids on the road, so would be nice they fit our model

Then  there is "Torque distribution between front and rear axle in percent.", so how would you do real Torque Vectoring of individual wheels?

**Comment by erikbosch** [comment]
With my understanding the electrical drive of a Toyota HSD is always connected, i.e. iof the car is moving the engine is rotating, so then "IsElectricalPowertrainEngaged" is always true, if it is mechanical connection we talk about.

I do not know how Torque vectoring is managed, if it is managed by several layers (e.g. first vectoring on axle level, then on wheel level for each axle). I will check with Mischa for comments

**Comment by SebastianSchildt** [comment]
Found this https://www.heise.de/autos/artikel/P0-bis-P3-wohin-mit-dem-E-Motor-4179135.html  
@erikbosch may tax your german skills, but gives general topology options for hybrids

**Comment by erikbosch** [comment]
Yes, and from there it seems that electrical motor never is mechanically disconnected from the rest of the vehicle. I will need to check with Mischa how this signal is supposed to work.

**Comment by erikbosch** [comment]
Will be replaced with an "official" PR

**Pull request closed without merging**
